include dracula.conf
background_opacity 0.75
background_blur 3

shell            /bin/fish

font_size 15.0
font_family      0xProto Nerd Font Mono
font_bold        0xProto Nerd Font Mono


enable_audio_bell no

editor nvim
