envs:
  - DOTFILES_PATH: $HOME/.dotfiles/
  - DOTFILES_PATH: $HOME/.dotfiles/
  - STOW_DIR: $DOTFILES_PATH
  - STARSHIP_CONFIG: $DOTFILES_PATH/.config/starship/themes/wordful.toml
  - STARSHIP_THEME: $STARSHIP_CONFIG
  - ASDF_SHIMS_PATH: $HOME/.asdf/shims/
  - PATH: $PATH:$HOME/.local/bin/:$ASDF_SHIMS_PATH
  - SUDO_PROMPT: "
    \e[0;36mâ•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®\e[0m\n
    \e[0;36mâ”‚\e[0m              \e[1;33m<<< \e[1;32mðŸ›¡ï¸ Password Required \e[1;33m>>>              \e[0m\e[0;36mâ”‚\e[0m\n
    \e[0;36mâ”‚â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯\e[0m\n
    \e[0;36mâ”‚\n
    \e[0;36mâ•°â”€â•¼\e[0m
  "
